### PR TITLE
Updated numbering to start at 0.

### PR DESCRIPTION
**Pull request by Hou5e**
I updated the main bullet points to start with 0, instead of 1.
I also synchronized a few minor changes between the different copies of each file.

Please update the links to point to the newer repo locations for the documents on this page:
https://lslspanish.github.io/translation_GPLv3_to_spanish/

Thanks!

### CODE REVIEW

**Comment by gregoriorobles** [comment]
thanks, @Hou5e, for the PR. Could you please tell me with more detail where I have to update the links?

**Comment by Hou5e** [comment]
It looks like the webpage was made with [GitHub Pages](http://pages.github.com/) for:
https://lslspanish.github.io/translation_GPLv3_to_spanish/

I have attached (2) HTML files (as TXT files) that you can file compare the text for the website homepage changes to update:
[current.txt](https://github.com/LSLSpanish/translation_GPLv3_to_spanish/files/10071940/current.txt) = Existing website HTML code
[updated.txt](https://github.com/LSLSpanish/translation_GPLv3_to_spanish/files/10071939/updated.txt) = Changes to update

There is a separate old copy of the files for the webpage at:
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.txt
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.tex
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.odt
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.pdf
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.html

Those files should be updated from the files at:
https://github.com/LSLSpanish/translation_GPLv3_to_spanish/tree/master/Versi%C3%B3n%20definitiva

Thanks!

**Comment by Hou5e** [comment]
Optional improvements: In all the license files, I would suggest to move the title text below the "This is an unofficial translation..." disclaimer, and add the notice: “You may publish this translation, modified or unmodified, only under the terms at[ http://www.gnu.org/licenses/translations.html](https://www.gnu.org/licenses/translations.html).” (Item 5. from the list on that webpage)

Like example: [Basque translation of the GPL](https://www.euskadi.eus/contenidos/informacion/software_lizentziak_2018/eu_def/adjuntos/gnu-gpl-v3.eu.html)

This line that was added conflicts with that, and probably should be removed:
Se permite la copia y distribución de copias literales de este documento, pero no se permite su modificación.

**Comment by gregoriorobles** [comment]
Thanks, @Hou5e. It took time, but I managed to updated the gh-pages.

**Comment by Hou5e** [comment]
Nice. It looks good. 👍 

image
The couple files that are linked-to near the top of the page look like they could use updating from the GitHub files at:
https://github.com/LSLSpanish/translation_GPLv3_to_spanish/tree/master/Versi%C3%B3n%20definitiva

To Update:
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.txt
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.odt
https://lslspanish.github.io/translation_GPLv3_to_spanish/files/GPLv3-spanish.html
(The main numbering is 1-18, and should be 0-17 for these files)

**Comment by gregoriorobles** [comment]
Oh, I see, I've uploaded the new versions to the gh-pages. Thanks again!

**Pull request merged**
